version: '3.9'

services:

  postgres:
    build: 
      context: .
      dockerfile: ./resources/Dockerfile.db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports: 
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./pgdata:/root

volumes:
  postgres-db: